In [1]:
import pandas as pd

In [4]:
data=pd.read_csv(r"C:\Users\Trainer1.FTDC\Downloads\Car_details(U).csv")

In [5]:
data

,vehicle_uid,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,car_record_id,car_age,price_category,km_category,owner_count,fuel_transmission,brand,price_per_km,is_diesel
0,CAR_000001,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner,1,18,Low,NaN,0.0,Petrol_Manual,Maruti,0.86,0
1,CAR_000002,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,NaN,Individual,Manual,First Owner,2,18,Low,NaN,0.0,Petrol_Manual,Maruti,2.70,0
2,CAR_000003,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner,3,13,NaN,NaN,NaN,Diesel_Manual,Hyundai,6.00,1
3,CAR_000004,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner,4,8,Low,Medium,0.0,Petrol_Manual,Datsun,5.43,0
4,CAR_000005,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner,5,11,NaN,High,0.0,Diesel_Manual,Honda,3.19,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,CAR_004336,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,NaN,Diesel,Individual,Manual,Second Owner,4336,11,Mid,High,0.0,Diesel_Manual,Hyundai,5.12,1
4336,CAR_004337,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,Diesel,Individual,NaN,Second Owner,4337,11,Mid,High,0.0,Diesel_Manual,Hyundai,5.12,1
4337,CAR_004338,Maruti 800 AC BSIII,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner,4338,16,Low,High,NaN,Petrol_Manual,Maruti,1.33,0
4338,CAR_004339,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,NaN,Diesel,Individual,Manual,First Owner,4339,9,High,High,0.0,Diesel_Manual,Hyundai,9.61,1
4339,CAR_004340,Renault KWID RXT,2016,NaN,40000.0,Petrol,Individual,Manual,First Owner,4340,9,Low,Medium,0.0,Petrol_Manual,Renault,5.62,0

In [7]:
data.isnull().any()

vehicle_uid          False
name                 False
year                 False
selling_price         True
km_driven             True
fuel                  True
seller_type          False
transmission          True
owner                False
car_record_id        False
car_age              False
price_category        True
km_category           True
owner_count           True
fuel_transmission    False
brand                False
price_per_km         False
is_diesel            False
dtype: bool

In [8]:
data.isnull().sum()

vehicle_uid            0
name                   0
year                   0
selling_price        434
km_driven            434
fuel                 435
seller_type            0
transmission         434
owner                  0
car_record_id          0
car_age                0
price_category       434
km_category          434
owner_count          434
fuel_transmission      0
brand                  0
price_per_km           0
is_diesel              0
dtype: int64

In [12]:
smax=data['selling_price'].max()

In [13]:
smin=data['selling_price'].min()

In [15]:
Savg=(smax+smin)/2

In [18]:
data['selling_price'].fillna(Savg,inplace=True)

In [17]:
import warnings
warnings.filterwarnings("ignore")

In [19]:
data.isnull().sum()

vehicle_uid            0
name                   0
year                   0
selling_price          0
km_driven            434
fuel                 435
seller_type            0
transmission         434
owner                  0
car_record_id          0
car_age                0
price_category       434
km_category          434
owner_count          434
fuel_transmission      0
brand                  0
price_per_km           0
is_diesel              0
dtype: int64

In [20]:
#Q2

In [22]:
data.describe()

,year,selling_price,km_driven,car_record_id,car_age,owner_count,price_per_km,is_diesel
count,4340.000000,4.340000e+03,3906.000000,4340.000000,4340.000000,3906.0,4340.000000,4340.000000
mean,2013.090783,9.027308e+05,66231.222990,2170.500000,11.909217,0.0,88.013984,0.496083
std,4.215344,1.311959e+06,47047.819626,1252.994413,4.215344,0.0,3801.519948,0.500042
min,1992.000000,2.200000e+04,1.000000,1.000000,5.000000,0.0,0.250000,0.000000
25%,2011.000000,2.250000e+05,35000.000000,1085.750000,9.000000,0.0,2.620000,0.000000
50%,2014.000000,4.000000e+05,60000.000000,2170.500000,11.000000,0.0,6.000000,0.000000
75%,2016.000000,7.500000e+05,90000.000000,3255.250000,14.000000,0.0,15.555000,1.000000
max,2020.000000,8.900000e+06,806599.000000,4340.000000,33.000000,0.0,250000.000000,1.000000

In [23]:
data["km_driven"].mean()

66231.22299027137

In [24]:
data["km_driven"].fillna(data["km_driven"].mean(),inplace=True)

In [26]:
data["owner_count"].median()

0.0

In [27]:
data["owner_count"].fillna(0,inplace=True)

In [28]:
data.isnull().sum()

vehicle_uid            0
name                   0
year                   0
selling_price          0
km_driven              0
fuel                 435
seller_type            0
transmission         434
owner                  0
car_record_id          0
car_age                0
price_category       434
km_category          434
owner_count            0
fuel_transmission      0
brand                  0
price_per_km           0
is_diesel              0
dtype: int64

In [30]:
data["km_category"].mode()

0    Medium
Name: km_category, dtype: object

In [32]:
data["km_category"].isnull().sum()

434

In [33]:
434/2

217.0

In [35]:
data["km_category"].fillna(data["km_category"].mode()[0],limit=217,inplace=True)

In [36]:
data["km_category"].isnull().sum()

217

In [37]:
data["km_category"].fillna("High",inplace=True)

In [38]:
data["km_category"].isnull().sum()

0

In [39]:
data.isnull().sum()

vehicle_uid            0
name                   0
year                   0
selling_price          0
km_driven              0
fuel                 435
seller_type            0
transmission         434
owner                  0
car_record_id          0
car_age                0
price_category       434
km_category            0
owner_count            0
fuel_transmission      0
brand                  0
price_per_km           0
is_diesel              0
dtype: int64

In [ ]:
#Q4

In [40]:
data.head()

,vehicle_uid,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,car_record_id,car_age,price_category,km_category,owner_count,fuel_transmission,brand,price_per_km,is_diesel
0,CAR_000001,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner,1,18,Low,Medium,0.0,Petrol_Manual,Maruti,0.86,0
1,CAR_000002,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,NaN,Individual,Manual,First Owner,2,18,Low,Medium,0.0,Petrol_Manual,Maruti,2.70,0
2,CAR_000003,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner,3,13,NaN,Medium,0.0,Diesel_Manual,Hyundai,6.00,1
3,CAR_000004,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner,4,8,Low,Medium,0.0,Petrol_Manual,Datsun,5.43,0
4,CAR_000005,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner,5,11,NaN,High,0.0,Diesel_Manual,Honda,3.19,1

In [41]:
data["transmission"].unique()

array(['Manual', nan, 'Automatic'], dtype=object)

In [44]:
modeP=data["price_category"].mode()

In [48]:
data['price_category'].fillna(modeP[0],inplace=True)

In [49]:
data["transmission"].fillna("Unknown",inplace=True)

In [50]:
data.isnull().sum()

vehicle_uid            0
name                   0
year                   0
selling_price          0
km_driven              0
fuel                 435
seller_type            0
transmission           0
owner                  0
car_record_id          0
car_age                0
price_category         0
km_category            0
owner_count            0
fuel_transmission      0
brand                  0
price_per_km           0
is_diesel              0
dtype: int64

In [51]:
#Q5

In [52]:
data["fuel"].unique()

array(['Petrol', nan, 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [53]:
435/5

87.0

In [54]:
data["fuel"].fillna("Petrol",limit=87,inplace=True)

In [55]:
data["fuel"].fillna("Diesel",limit=87,inplace=True)

In [56]:
data["fuel"].fillna("CNG",limit=87,inplace=True)

In [57]:
data["fuel"].fillna("LPG",limit=87,inplace=True)

In [59]:
data["fuel"].fillna("Electric",limit=87,inplace=True)

In [61]:
data.isnull().any()

vehicle_uid          False
name                 False
year                 False
selling_price        False
km_driven            False
fuel                 False
seller_type          False
transmission         False
owner                False
car_record_id        False
car_age              False
price_category       False
km_category          False
owner_count          False
fuel_transmission    False
brand                False
price_per_km         False
is_diesel            False
dtype: bool

In [62]:
data.isnull().sum()

vehicle_uid          0
name                 0
year                 0
selling_price        0
km_driven            0
fuel                 0
seller_type          0
transmission         0
owner                0
car_record_id        0
car_age              0
price_category       0
km_category          0
owner_count          0
fuel_transmission    0
brand                0
price_per_km         0
is_diesel            0
dtype: int64

In [64]:
data.to_csv("cars_Ml.csv",index=False)

In [65]:
pwd

'C:\\Users\\Trainer1.FTDC'

In [69]:
data[["vehicle_uid", "name", "year", "fuel", "seller_type", "transmission", "owner","brand", "car_age"]].to_csv("vehicle_info.csv",index=False)

In [68]:
cd Downloads

C:\Users\Trainer1.FTDC\Downloads

In [71]:
data[["vehicle_uid", "selling_price", "km_driven", "price_category",
"km_category"]].to_csv("vehicle_sales.csv",index=False)